/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#include "nsISupports.idl"
interface nsIObserver;

/** Profile-wide storage operations, independent of open content views. */
[scriptable, uuid(2189fd59-8051-4d99-986e-dac628e301ef)]
interface nsIContentStorage : nsISupports
{
  /** Clear cookies in all normal, container and active private sessions.
   * Completion topic is content-storage-cookies-cleared; data is success/error.
   * A synchronous error means no callback will be delivered.
   */
  void clearCookies(in nsIObserver completion);
};
