name: Build Basilisk

on:  
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-basilisk:
    name: Build Basilisk ${{ matrix.config.name }} x86_64
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: GTK3-x86_64
          gtk: gtk3
          arch: x86_64
        - name: GTK2-x86_64
          gtk: gtk2
          arch: x86_64
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install build-essential libgtk2.0-dev libdbus-glib-1-dev \
          yasm libegl1-mesa-dev libasound2-dev libxt-dev zlib1g-dev libssl-dev \
          libsqlite3-dev libbz2-dev libpulse-dev libgconf2-dev libx11-xcb-dev \
          zip python2.7 python-dbus-dev libgtk-3-dev autoconf2.13 -y

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Copy mozconfig
        run: cp .github/workflows/build-basilisk/mozconfig-${{ matrix.config.gtk }}-${{ matrix.config.arch }} .mozconfig

      - name: mach configure
        run: ./mach configure

      - name: mach build
        run: ./mach build

      - name: mach package
        run: ./mach package

      - uses: actions/upload-artifact@v3
        with:
          name: basilisk-linux-${{ matrix.config.arch }}-${{ matrix.config.gtk }}
          path: obj-${{ matrix.config.arch }}-pc-linux-gnu/dist/basilisk-*