name: Build Basilisk

on:  
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-basilisk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update
          sudo apt-get install -y build-essential libgtk2.0-dev libssl-dev \
          libdbus-glib-1-dev autoconf2.13 yasm libegl1-mesa-dev libasound2-dev \
          libxt-dev zlib1g-dev libsqlite3-dev libbz2-dev libpulse-dev zip \
          libgconf2-dev libx11-xcb-dev python2.7 python-dbus

      - name: Copy mozconfig
        run: cd basilisk-mirror && cp .github/workflows/build-basilisk/mozconfig-gtk3-x86_64 .mozconfig

      - name: mach configure
        run: ./mach configure

      - name: mach build
        run: ./mach build

      - name: mach package
        run: ./mach package

      - uses: actions/upload-artifact@v3
        with:
          name: basilisk-linux-x86_64
          path: basilisk-mirror/obj-x86_64-pc-linux-gnu/dist/basilisk-*