name: Build Basilisk x86_64

on:  
  workflow_dispatch:
  push:
    branches:
      - master
      - release

jobs:
  build-basilisk:
    name: Build Basilisk ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: GTK3 x86_64
          gtk: gtk3
          arch: x86_64
        - name: GTK2 x86_64
          gtk: gtk2
          arch: x86_64
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Copy mozconfig
        run: cp .github/workflows/build-basilisk/mozconfig-${{ matrix.config.gtk }}-${{ matrix.config.arch }} .mozconfig

      - name: Build Basilisk
        run: docker run -v $PWD:/share --rm -e UPDATEFIRST=$UPDATEFIRST -e UID=$(id -u) -e GID=$(id -g) -e USERNAME=$(whoami) -e GROUPNAME=$(id -gn) -t basiliskdev/slackware14-uxp:latest /share/build-scripts/linux-x86_64/build_basilisk_subscripts/run_inside_docker.sh

      - uses: actions/upload-artifact@v3
        with:
          name: basilisk-linux-${{ matrix.config.arch }}-${{ matrix.config.gtk }}
          path: obj-${{ matrix.config.arch }}-pc-linux-gnu/dist/basilisk-*